version: '3.8'

services:
  asneg-demo:
    container_name: asneg-demo${BUILD_TAG}
    hostname: asneg-demo
    image: asneg/asneg-demo:release-4
    expose:
      - "8889"
      - "4840"
    ports:
      - "0.0.0.0:8889:8889"
      - "0.0.0.0:4840:4840"
    volumes:
      - demo_server_pki:/etc/OpcUaStack/ASNeG-Demo/pki

  webserver:
    container_name: webserver${BUILD_TAG}
    hostname: webserver
    depends_on:
      - asneg-demo
    expose:
      - "8080"
      - "8081"
      - "8082"
      - "22"
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:8082:8082"
      - "0.0.0.0:8890:8890"
      - "0.0.0.0:22:22"
    environment:
      - SERVER_PKI_ROOT_DIR=/tmp/
      - SSH_AUTH_SOCK=/ssh-agent
    build: ../OpcUaWebServer
    volumes:
      - web_server_pki:/etc/OpcUaStack/OpcUaWebServer/pki
      - .:/code
    command: >-
      bash -c "sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClient0.xml
      && sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClient1.xml 
      && sed -i 's/0.0.0.0:8889/asneg-demo:8889/' /etc/OpcUaStack/OpcUaWebServer/OpcUaClientTest.xml
      && OpcUaServer4 /etc/OpcUaStack/OpcUaWebServer/OpcUaServer.xml"

  test_client:
    container_name: test_client${BUILD_TAG}
    build: ../OpcUaWebServer
    depends_on:
      - asneg-demo
      - webserver
    environment:
      - SERVER_PKI_ROOT_DIR=/tmp/
      - WSS_GATEWAY_URL=wss://0.0.0.0:8082
      - WS_GATEWAY_URL=ws://0.0.0.0:8082
      - WSS_SERVER_URL=wss://0.0.0.0:8081
      - WS_SERVER_URL=ws://0.0.0.0:8081
      - OPC_SERVER_URL=opc.tcp://0.0.0.0:8889
      - DOCKER_ENABLE=YES
    command: echo "Test client is ready"
    volumes:
      - web_server_pki:/tmp/etc/OpcUaStack/OpcUaWebServer/pki
      - demo_server_pki:/tmp/etc/OpcUaStack/ASNeG-Demo/pki
      - .:/code

volumes:
  demo_server_pki:
  web_server_pki:
